version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
  - source: /ecom.sql
    destination: /tmp/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: admin
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 30
      runas: admin
    - location: scripts/db-load.sh
      timeout: 60
      runas: admin
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: admin
